exclude_paths:
- "Gruntfile.js"

engines:
  # ... CONFIG CONTENT ...
  csslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      important:
        enabled: false
# ... CONFIG CONTENT ...
