language: node_js
node_js:
  - '6'
  
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search

before_script:
  - npm install grunt-cli -g
  - npm install

script:
  - grunt commit
